"""Writes every logo file from the typeface outlines, so the logo exists in exactly one place.
usage: python docs/assets/brand/src/build_logo.py     (needs fontTools; then `sh docs/assets/brand/src/build.sh` for the PNGs)

Outputs: docs/assets/brand/{wordmark,wordmark-on-dark,wordmark-animated,wordmark-animated-on-dark,mark,mark-bare,favicon}.svg,
         markbook/web/static/favicon.svg, and the logo macros in markbook/web/templates/_ui.html."""
import re
from pathlib import Path

from make_logo import outlines

ROOT = Path(__file__).resolve().parents[4]
BRAND = ROOT / "docs" / "assets" / "brand"
INK, GREEN, PAPER = "#10223A", "#19B37D", "#FBFAF6"

WORD, WB = outlines("Markbook", size=100)
M, _ = outlines("M", size=50, origin=(6, 46))                 # the M, placed inside a 64 x 64 tile
TICK_WORD = "M386 -30L401 -12L432 -58"                         # the tick that ends the signature
TICK_ICON = "M44 37L50 43.5L60 26"
WORD_VIEW = "-4 -78 446 92"


def svg(view, body, extra="", label="Markbook"):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}" role="img" aria-label="{label}">{extra}{body}</svg>\n'


def wordmark(fg, animated=False):
    word = f'<path class="word" d="{WORD}" fill="{fg}"/>'
    tick = f'<path class="tick" pathLength="1" d="{TICK_WORD}" fill="none" stroke="{GREEN}" stroke-width="11" stroke-linecap="round" stroke-linejoin="round"/>'
    if not animated:
        return svg(WORD_VIEW, word + tick)
    css = ("<style>"
           ".word{animation:write 8s ease-in-out infinite}.tick{stroke-dasharray:1;animation:tick 8s ease-in-out infinite}"
           "@keyframes write{0%,4%{clip-path:polygon(0 0,0 0,-14% 100%,0 100%)}24%,92%{clip-path:polygon(0 0,114% 0,100% 100%,0 100%)}98%,100%{clip-path:polygon(0 0,114% 0,100% 100%,0 100%)}}"
           "@keyframes tick{0%,23%{stroke-dashoffset:1}31%,100%{stroke-dashoffset:0}}"
           "@media (prefers-reduced-motion:reduce){.word,.tick{animation:none!important;clip-path:none!important;stroke-dashoffset:0!important}}"
           "</style>")
    return svg(WORD_VIEW, word + tick, css)


def mark_body(fg, tick, tile=None, m_stroke=1.25, tick_w=5.5):
    t = f'<rect width="64" height="64" rx="15" fill="{tile}"/>' if tile else ""
    return (t + f'<path class="m" d="{M}" fill="{fg}" stroke="{fg}" stroke-width="{m_stroke}" stroke-linejoin="round"/>'
            f'<path class="tk" d="{TICK_ICON}" fill="none" stroke="{tick}" stroke-width="{tick_w}" stroke-linecap="round" stroke-linejoin="round"/>')


def write(path, text):
    path.write_text(text)
    print("wrote", path.relative_to(ROOT))


write(BRAND / "wordmark.svg", wordmark(INK))
write(BRAND / "wordmark-on-dark.svg", wordmark(PAPER))
write(BRAND / "wordmark-animated.svg", wordmark(INK, True))
write(BRAND / "wordmark-animated-on-dark.svg", wordmark(PAPER, True))
write(BRAND / "mark.svg", svg("0 0 64 64", mark_body(PAPER, GREEN, tile=INK)))
write(BRAND / "mark-bare.svg", svg("3 7 60 46", mark_body(INK, GREEN)))
fav = svg("0 0 64 64", mark_body(PAPER, GREEN, tile=INK, m_stroke=2.6, tick_w=7.5))
write(BRAND / "favicon.svg", fav)
write(ROOT / "markbook" / "web" / "static" / "favicon.svg", fav)
for old in ("mark-animated.svg",):
    (BRAND / old).unlink(missing_ok=True)

# the web UI's inline copies (the CSP forbids loading an <svg> as markup from a file, and this keeps them tested against the files above)
macros = f'''{{# logo:start (generated by docs/assets/brand/src/build_logo.py; do not edit by hand) #}}
{{% macro mark(cls="") -%}}
<svg class="mark {{{{ cls }}}}" viewBox="3 7 60 46" aria-hidden="true" focusable="false">
  <path class="m" d="{M}" stroke-width="1.25" stroke-linejoin="round"/>
  <path class="tk" d="{TICK_ICON}" stroke-width="5.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
{{%- endmacro %}}

{{% macro wordmark(cls="") -%}}
<svg class="wm {{{{ cls }}}}" viewBox="{WORD_VIEW}" aria-hidden="true" focusable="false">
  <path class="word" d="{WORD}"/>
  <path class="tick" pathLength="1" d="{TICK_WORD}" stroke-width="11" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
{{%- endmacro %}}
{{# logo:end #}}'''
ui = ROOT / "markbook" / "web" / "templates" / "_ui.html"
text = ui.read_text()
if "{# logo:start" in text:
    text = re.sub(r"\{# logo:start.*?\{# logo:end #\}", lambda _: macros, text, flags=re.S)
else:
    text = re.sub(r"\{% macro mark.*?\{%- endmacro %\}", lambda _: macros, text, count=1, flags=re.S)
ui.write_text(text)
print("patched", ui.relative_to(ROOT))
